apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-java-springboot-basic-pgml
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/fduthill-tenant/devfile-sample-java-springboot-basic/devfile-sample-java-springboot-basic-pgml@sha256:185b606ed6b0533741cb9377a7be18bfa35a4076e574edba9002b2fd670cbecd
        name: my-java-springboot
        resources: {}
status: {}
